---
title: "Ecological"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r load}
library(readxl)
library(dplyr)
library(tibble)

# ec <- read_excel("./ecological.xlsx", sheet = 1) %>% mutate(crash=as.logical(crash))
# head(ec)

ec <- frame_data(
  ~income, ~group, ~crash,
  34000,"A",TRUE,
  52000,"A",TRUE,
  57000,"A",FALSE,
  70000,"A",FALSE,
  58000,"A",FALSE,
  37000,"A",TRUE,
  44000,"A",TRUE,
  25000,"B",FALSE,
  22000,"B",FALSE,
  18000,"B",TRUE,
  48000,"B",FALSE,
  56000,"B",FALSE,
  21000,"B",TRUE,
  20000,"B",TRUE,
  16000,"C",FALSE,
  17000,"C",FALSE,
  23000,"C",FALSE,
  11000,"C",TRUE,
  15000,"C",TRUE,
  34000,"C",FALSE,
  25000,"C",FALSE
)

```

## Including Plots

You can also embed plots, for example:

```{r summarise, echo=FALSE}
library(dplyr)
bygrp <- ec %>% group_by(group) %>% summarise(income=mean(income), crash=mean(crash))
bycrash <- ec %>% group_by(crash) %>% summarise(income=mean(income))
byboth <- ec %>% group_by(group, crash) %>% summarise(income=mean(income))
```

```{r plots}
library(ggplot2)
bygrp %>% ggplot(aes(income,crash)) + geom_point() + geom_label(aes(label=group, colour=group))
bycrash %>% ggplot(aes(crash, income)) + geom_bar(stat="identity")
ec %>% ggplot(aes(group, income, group=group, colour=crash)) + geom_point()
byboth %>% ggplot(aes(group, income, fill=crash)) + geom_bar(stat="identity", position="dodge")
bygrp %>% ggplot(aes(group, crash, fill=crash)) + geom_bar(stat="identity", position="dodge")
```

