---
title: "Polling"
runtime: shiny
output: ioslides_presentation
widescreen: yes
---

```{r setup, include=FALSE}
library(shiny)
library(grid)
library(scales)
library(ggplot2)
library(RColorBrewer)
library(data.table)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE, message=F, error=F, warning=F)

# load("poppref.RDa")
# poppref <- read_csv("poppref.csv")
poppref <- fread("poppref.csv", sep = ",")
poppref <- poppref %>%
  mutate(rownum = sample(1:1e8, length(poppref$strana), replace = F)) %>%
  arrange(rownum)
```

## Postupný sběr dat

```{r error=F, include=T}
vyber <- reactive(
  {pocetradek = as.numeric(input$pricist1 + input$pricist10*10 + 
                             input$pricist20*20 + input$pricist100*100)
  poppref[0:pocetradek,]
  }
)

inputPanel(
  actionButton("pricist1", label = "Ještě 1"),
  actionButton("pricist10", label = "Ještě 10"),
  actionButton("pricist20", label = "Ještě 20"),
  actionButton("pricist100", label = "Ještě 100")
  # actionButton(paste("Znova vybrat", nrow(vyber())))
)

souhrn_pop <- poppref %>% mutate(id=row_number()) %>% group_by(strana) %>%
  summarise(pocet=n()) %>% mutate(podil=pocet/sum(pocet))
```

```{r include=T, error=F}
themebar <- theme_minimal() +
  theme(text=element_text(size=24),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank())
partypal <- brewer.pal(4, "Set1")

renderPlot({souhrn_pop %>% ggplot(aes(x=1, y=podil, fill=strana)) +
    geom_bar(stat="identity", position="fill") + coord_flip() +
    geom_text(aes(label=paste(formatC(podil*100,digits = 2, width=0),"% "), y=podil, ymax=1),
              position="fill", hjust=1, size=8, colour="white", fontface="bold",
              show.legend = F) +
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green")) +
    themebar +
    guides(fill=guide_legend(title = "")) +
    scale_y_continuous(labels=percent) +
    theme(legend.position="bottom") +
    ggtitle("Skutečné preference")},width=1000, height=150)
 
# renderText({nrow(vyber())})
# renderText({input$pricist1})
# renderText({input$pricist10})
# renderText({input$pricist20})
# renderText({input$pricist100})

renderPlot({
  ggplot(vyber() %>% group_by(strana) %>%
           summarise(hlasy=n()) %>% ungroup() %>% mutate(podil=hlasy/sum(hlasy)),
         aes(x=1, y=podil, fill=strana)) +
    geom_bar(stat="identity", position="fill") +
    geom_text(aes(label=paste(formatC(podil*100,digits = 2, width=0),"%"),
                           y=podil, ymax=1, x=1),
              position="fill",hjust=1, size=8, colour="white", fontface="bold",
              show.legend = F, inherit.aes = F) +
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green")) +
    scale_y_continuous(labels=percent) +
    ggtitle(paste("Vzorek celkem", nrow(vyber()))) + coord_flip() + themebar +
    theme(legend.position="none")}, height=110, width=1000)

srovnani <- reactive({
  partycomp <- souhrn_pop %>% left_join(vyber() %>%
                                          group_by(strana) %>%
                                          summarise(hlasy=n()) %>%
                                          mutate(podil_vyber = hlasy/sum(hlasy))) %>%
  mutate(podil_vyber = ifelse(is.na(podil_vyber),0,podil_vyber)) %>% 
  mutate(rozdil = podil_vyber - podil)
  
  partycomp %>% bind_rows(partycomp %>%
                            ungroup() %>%
                            summarise(rozdil=mean(abs(rozdil))) %>% 
                            mutate(strana="Průměrná absolutní chyba"))})
  
```

```{r eval=T}
renderPlot({srovnani() %>%
  ggplot(aes(strana, rozdil, fill=strana)) +
    geom_bar(stat="identity") + themebar + coord_flip() +
    geom_hline(yintercept=0) +
    geom_text(aes(label=paste(formatC(rozdil*100,digits = 2, width=0),"%"),
              y=rozdil+(ifelse(rozdil>0, .05, -0.05))), size=6) +
    scale_y_continuous(limits=c(-0.75, 0.75), labels=percent) +
    theme(legend.position="none", axis.text.y=element_text(hjust=1)) +
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green",
                               "Průměrná absolutní chyba"="grey"))},
  width=600, height=150)
```

```{r results="asis", include=F, eval=F}
renderTable(srovnani())
```

## Několik průzkumů o 100 respondentech

```{r}

osmkratsto <- bind_rows(data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 1"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 2"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 3"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 4"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 5"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 6"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 7"),
                        data_frame("strana"=sample(poppref$strana, 100, replace=F),
                                   "pruzkum" = "Pruzkum 8")
                        )

renderPlot({souhrn_pop %>%
    ggplot(aes(x="         ", y=podil, fill=strana)) +
    geom_bar(stat="identity", position="fill") + coord_flip() +
    geom_text(aes(label=paste(formatC(podil*100,digits = 2, width=0),"% "), y=podil, ymax=1),
              position="fill", hjust=1, size=8, colour="white", fontface="bold",
              show.legend = F) +
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green")) +
    themebar +
    guides(fill=guide_legend(title = "")) +
    scale_y_continuous(labels=percent) +
    theme(legend.position="bottom", axis.text.y=element_text(family="Courier"),
           axis.text.x=element_text()) +
    ggtitle("Skutečné preference")},width=1000, height=150)

osmkratsto_sum <- osmkratsto %>%
  group_by(pruzkum, strana) %>%
  summarise(pocet = n()) %>% 
  ungroup() %>% group_by(pruzkum) %>%
  mutate(podil=pocet/sum(pocet))

renderPlot({ggplot(osmkratsto_sum, aes(fill=strana, x=pruzkum, y=podil)) +
    geom_bar(stat="identity", position="fill") +
    geom_text(aes(label=paste(formatC(podil*100,digits = 2, width=0),"% "), y=podil, ymax=1),
              position="fill", hjust=1, size=8, colour="white", fontface="bold",
              show.legend = F) +
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green")) +
    scale_y_continuous(labels=percent) +
    # ggtitle("Osm průzkumů o 100 respondentech") +
    coord_flip() + themebar +
    theme(legend.position="none", axis.text.y=element_text(family="Courier"),
          axis.text.x=element_text())},width=1000, height=250)

osmkratsto_comp <- osmkratsto_sum %>%
  group_by(strana) %>%
  left_join(souhrn_pop %>% group_by(strana) %>% select(podil_pop=podil), by = c("strana")) %>% 
  mutate(rozdil = abs(podil - podil_pop)) %>% 
  summarise(meanrozdil = mean(rozdil))

osmkratsto_comp <- osmkratsto_comp %>% bind_rows(osmkratsto_comp %>%
                               ungroup() %>%
                               summarise(meanrozdil=mean(meanrozdil)) %>% 
                               mutate(strana="Průměrná absolutní chyba"))
```

```{r results="asis", include=F, eval=F}
renderTable(osmkratsto_comp)
```

Průměrná absolutní chyba: `r paste(formatC(osmkratsto_comp$meanrozdil[[4]]*100,digits = 2, width=0),"% ")`

## Několik průzkumů o 1000 respondentech

```{r}
osmkrattisic <- bind_rows(data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 1"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 2"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 3"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 4"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 5"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 6"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 7"),
                        data_frame("strana"=sample(poppref$strana, 1000, replace=F),
                                   "pruzkum" = "Pruzkum 8")
                        )

renderPlot({souhrn_pop %>% ggplot(aes(x="         ", y=podil, fill=strana)) +
    geom_bar(stat="identity", position="fill") + coord_flip() +
    geom_text(aes(label=paste(formatC(podil*100,digits = 2, width=0),"% "), y=podil, ymax=1),
              position="fill", hjust=1, size=8, colour="white", fontface="bold",
              show.legend = F) +
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green")) +
    themebar +
    guides(fill=guide_legend(title = "")) +
    scale_y_continuous(labels=percent) +
    theme(legend.position="bottom", axis.text.y=element_text(family="Courier"),
           axis.text.x=element_text()) +
    ggtitle("Skutečné preference")},width=1000, height=150)

osmkrattisic_sum <- osmkrattisic %>% group_by(pruzkum, strana) %>%
         summarise(pocet = n()) %>% 
         ungroup() %>% group_by(pruzkum) %>% mutate(podil=pocet/sum(pocet))

renderPlot({ggplot(osmkrattisic_sum, aes(fill=strana, x=pruzkum, y=podil)) +
    geom_bar(stat="identity", position="fill") +
    geom_text(aes(label=paste(formatC(podil*100,digits = 2, width=0),"% "), y=podil, ymax=1),
              position="fill", hjust=1, size=8, colour="white", fontface="bold",
              show.legend = F) +  
    scale_fill_manual(values=c("Strana jistot"="red",
                               "Strana prosperity"="blue",
                               "Strana života"="green")) +
    scale_y_continuous(labels=percent) +
    # ggtitle("Osm průzkumů o 100 respondentech") +
    coord_flip() + themebar +
    theme(legend.position="none", axis.text.y=element_text(family="Courier"),
          axis.text.x=element_text())}, width=1000, height=250)

osmkrattisic_comp <- osmkrattisic_sum %>%
  group_by(strana) %>%
  left_join(souhrn_pop %>% group_by(strana) %>% select(podil_pop=podil), by = c("strana")) %>% 
  mutate(rozdil = abs(podil - podil_pop)) %>% 
  summarise(meanrozdil = mean(rozdil))

osmkrattisic_comp <- osmkrattisic_comp %>% bind_rows(osmkrattisic_comp %>%
                               ungroup() %>%
                               summarise(meanrozdil=mean(meanrozdil)) %>% 
                               mutate(strana="Průměrná absolutní chyba"))
```

```{r results="asis", include=F, eval=F}
renderTable(osmkrattisic_comp)
```

Průměrná absolutní chyba: `r paste(formatC(osmkrattisic_comp$meanrozdil[[4]]*100,digits = 2, width=0),"% ")`